[코드ldy 5-1]

In [36]:
!pip install numpy;

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)

[코드ldy 5-2]

In [37]:
import numpy as np

list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape:', a.shape)
print('a[0]:', a[0])

a.shape: (4,)
a[0]: 1

[코드ldy 5-3]

In [38]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape:', b.shape)
print('b[0, 0]:', b[0, 0])
print('b[0]:', b[0])

b.shape: (2, 3)
b[0, 0]: 1
b[0]: [1 2 3]

[코드ldy 5-4]

In [39]:
import numpy as np

b = np.arange(4)
print('b.shape:\n', b.shape)
print(b)

b.shape:
 (4,)
[0 1 2 3]

[코드ldy 5-5]

In [40]:
import numpy as np

a = np.array([1, 2], dtype=np.float64)
print(a.dtype)
print('a\n', a)

a_i8 = a.astype(np.int8)
print(a_i8.dtype)
print('a_i8\n', a_i8)

float64
a
 [1. 2.]
int8
a_i8
 [1 2]

[코드ldy 5-6]

In [41]:
import numpy as np

arr = np.array([[20260930, 1, 2], [3, 4, 5]])
print('tpye(arr):', type(arr))
print('arr.ndim:', arr.ndim)
print('arr.dtype:', arr.dtype)
print('arr.size:', arr.size)
print('arr.shape:', arr.shape)

tpye(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.size: 6
arr.shape: (2, 3)

[코드ldy 5-7]

In [42]:
!pip install pandas;
import pandas as pd

a = pd.Series([7, 8])
print(a)
b = pd.Series([10, 11], index=['a', 'b'])
print(b)

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
0    7
1    8
dtype: int64
a    10
b    11
dtype: int64

[코드ldy 5-8]

In [43]:
list1 = list([['한빛', '남자'], ['한결', '남자']])
col_names = ['이름', '성별']
pd.DataFrame(list1, columns=col_names)

   이름  성별
0  한빛  남자
1  한결  남자

[코드ldy 5-9]

In [44]:
dict1 = {'이름': {0: '한빛', 1:'한결'}, '성별': {0: '남자', 1:'여자'}}
pd.DataFrame(dict1)

   이름  성별
0  한빛  남자
1  한결  여자

[코드ldy 5-10]

In [45]:
import numpy as np

arr1 = np.array([['한빛', '남자'], ['한결', '여자']])

col_names = ['이름', '성별']

pd.DataFrame(arr1, columns=col_names)

   이름  성별
0  한빛  남자
1  한결  여자

[코드ldy 5-11]

In [46]:
import numpy as np

list1 = list([['이동열', '남자'], ['이가원', '여자'], ['배규민', '남자']])
col_names = ['이름', '성별']
df = pd.DataFrame(list1, columns=col_names)
df

    이름  성별
0  이동열  남자
1  이가원  여자
2  배규민  남자

[코드ldy 5-12]

In [47]:
df.to_csv('약자_seris.csv', header=True, index=False, encoding='utf-8')
df2 = pd.read_csv('약자_seris.csv', sep=',')
df2.columns

Index(['이름', '성별'], dtype='object')

[코드ldy 5-13]

In [48]:
df2.head(2)

    이름  성별
0  이동열  남자
1  이가원  여자

In [49]:
df2.tail(1)

    이름  성별
2  배규민  남자

[코드ldy 5-14]

In [50]:
df[['이름']].head()

    이름
0  이동열
1  이가원
2  배규민

[코드ldy 5-15]

In [51]:
df.iloc[1:2, 0:1]

    이름
1  이가원

[코드ldy 5-16]

In [52]:
df.iloc[0:1, 0:1]

    이름
0  이동열

[코드ldy 5-17]

In [53]:
df[df['이름'] == '배규민'].head()

    이름  성별
2  배규민  남자

[코드ldy 5-18]

In [56]:
list1 = list([['이동열', '남자', 30, 183], ['이가원', '여자', 24, 162], ['배규민', '남자', 23, 179], ['고고림', '남자', 21, 182]])

col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)

df[df['키'] > 180]

    이름  성별  나이    키
0  이동열  남자  30  183
3  고고림  남자  21  182

[코드ldy 5-19]

In [57]:
df[(df['성별'] == '여자') & (df['키'] > 160)]

    이름  성별  나이    키
1  이가원  여자  24  162

[코드ldy 5-20]

In [58]:
df[df['이름'].str.contains('고')]

    이름  성별  나이    키
3  고고림  남자  21  182

[코드ldy 5-21]

In [59]:
df.loc[3, '키'] = df.loc[3, '키'] + 5
df.loc[[3]]

    이름  성별  나이    키
3  고고림  남자  21  187

[코드ldy 5-22]

In [60]:
df['보너스'] = df['나이'] * 10000
df.head(3)

    이름  성별  나이    키     보너스
0  이동열  남자  30  183  300000
1  이가원  여자  24  162  240000
2  배규민  남자  23  179  230000

[코드ldy 5-23]

In [61]:
df.drop('보너스', axis=1, inplace=True)
df.head(3)

    이름  성별  나이    키
0  이동열  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

[코드ldy 5-24]

In [62]:
df.reset_index(inplace=True)
df.head(3)

   index   이름  성별  나이    키
0      0  이동열  남자  30  183
1      1  이가원  여자  24  162
2      2  배규민  남자  23  179

[코드ldy 5-25]

In [65]:
import numpy as np

c = np.array([3, 5], dtype=np.float64)
print(c.dtype)
print('c\n', c)

d = np.arange(1, 18, 4)
print('\nd (arange)\n', d)

float64
c
 [3. 5.]

d (arange)
 [ 1  5  9 13 17]

[코드ldy 5-26]

In [73]:
import pandas as pd

data = {'k': [2, 3], 'M': [5, 6]}
df5 = pd.DataFrame(data)
print(df5.iloc[0:1, 0:2])
print(df5.loc[0:1])

   k  M
0  2  5
   k  M
0  2  5
1  3  6

[코드ldy 5-27]

In [81]:
import pandas as pd
list1 = list([['홍길동', '남자', 30, 183], ['이가원', '여자', 24, 162], ['배규민', '남자', 23, 179]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)
df.loc[[2]]

    이름  성별  나이    키
2  배규민  남자  23  179

[코드ldy 5-28]

In [82]:
import pandas as pd
list1 = list([['홍길동', '남자', 30, 183], ['배규민', '남자', 23, 179]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)

df['나이(일)'] = df['나이'] * 1000
print(df)

    이름  성별  나이    키  나이(일)
0  홍길동  남자  30  183  30000
1  배규민  남자  23  179  23000

[코드ldy 5-29]

In [85]:
import pandas as pd
list1 = list([['홍길동', '남자', 30, 183], ['배규민', '남자', 23, 179]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)

df.drop('성별', axis=1, inplace=True)
print(df)

    이름  나이    키
0  홍길동  30  183
1  배규민  23  179

[코드ldy 5-30]

In [88]:
import pandas as pd

list1 = list([['홍길동', '남자', 30, 183], ['배규민', '여자', 23, 179]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)

filtered_df = df[(df['성별'] == '여자')]
print(filtered_df)

    이름  성별  나이    키
1  배규민  여자  23  179